-- Tablas para ACC Construcción Admin

-- Categorías de trabajos
CREATE TABLE IF NOT EXISTS categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Trabajos (Proyectos)
CREATE TABLE IF NOT EXISTS trabajos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    descripcion TEXT,
    categoria_id BIGINT REFERENCES categorias(id),
    ubicacion TEXT,
    destacado BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Imágenes de trabajos
CREATE TABLE IF NOT EXISTS trabajo_imagenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trabajo_id BIGINT REFERENCES trabajos(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    es_principal BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Promociones
CREATE TABLE IF NOT EXISTS promociones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    descripcion TEXT,
    imagen_url TEXT,
    precio TEXT,
    ubicacion TEXT,
    habitaciones INTEGER,
    banos INTEGER,
    metros_cuadrados TEXT,
    etiqueta TEXT,
    etiqueta_color TEXT DEFAULT 'blue',
    activa BOOLEAN DEFAULT true,
    destacada BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Mensajes de contacto
CREATE TABLE IF NOT EXISTS mensajes_contacto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL,
    telefono TEXT,
    mensaje TEXT NOT NULL,
    leido BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Datos semilla (Seed data)
INSERT INTO categorias (nombre) VALUES 
('Edificación'), ('Obra Civil'), ('Reformas'), ('Mantenimiento')
ON CONFLICT (nombre) DO NOTHING;
